language: python
python:
  - "3.9"
install:
  - pip install -r api/requirements.txt
  - pip install -r lab/requirements.txt
  - export PYTHONPATH=`pwd`
  - pip install pytest-cov codecov  # install packages from code coverage
script:
  - pytest --cov=api/src tests # point to the source direcctory for the work in production
after_success:
  - codecov # uploads report to codecov.io